/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TheoryTopicSlugRouteImport } from './routes/theory/$topicSlug'
import { Route as CourseCourseSlugLessonSlugRouteImport } from './routes/course/$courseSlug/$lessonSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryTopicSlugRoute = TheoryTopicSlugRouteImport.update({
  id: '/theory/$topicSlug',
  path: '/theory/$topicSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseSlugLessonSlugRoute =
  CourseCourseSlugLessonSlugRouteImport.update({
    id: '/course/$courseSlug/$lessonSlug',
    path: '/course/$courseSlug/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/theory/$topicSlug': typeof TheoryTopicSlugRoute
  '/course/$courseSlug/$lessonSlug': typeof CourseCourseSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/theory/$topicSlug': typeof TheoryTopicSlugRoute
  '/course/$courseSlug/$lessonSlug': typeof CourseCourseSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/theory/$topicSlug': typeof TheoryTopicSlugRoute
  '/course/$courseSlug/$lessonSlug': typeof CourseCourseSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/theory/$topicSlug'
    | '/course/$courseSlug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/theory/$topicSlug'
    | '/course/$courseSlug/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/theory/$topicSlug'
    | '/course/$courseSlug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TheoryTopicSlugRoute: typeof TheoryTopicSlugRoute
  CourseCourseSlugLessonSlugRoute: typeof CourseCourseSlugLessonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/$topicSlug': {
      id: '/theory/$topicSlug'
      path: '/theory/$topicSlug'
      fullPath: '/theory/$topicSlug'
      preLoaderRoute: typeof TheoryTopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseSlug/$lessonSlug': {
      id: '/course/$courseSlug/$lessonSlug'
      path: '/course/$courseSlug/$lessonSlug'
      fullPath: '/course/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof CourseCourseSlugLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TheoryTopicSlugRoute: TheoryTopicSlugRoute,
  CourseCourseSlugLessonSlugRoute: CourseCourseSlugLessonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
