/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabDesignSystemRouteImport } from './routes/lab.design-system'
import { Route as LabLessonRouteImport } from './routes/lab.lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabDesignSystemRoute = LabDesignSystemRouteImport.update({
  id: '/lab/design-system',
  path: '/lab/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLessonRoute = LabLessonRouteImport.update({
  id: '/lab/lesson',
  path: '/lab/lesson',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab/design-system': typeof LabDesignSystemRoute
  '/lab/lesson': typeof LabLessonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab/design-system': typeof LabDesignSystemRoute
  '/lab/lesson': typeof LabLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab/design-system': typeof LabDesignSystemRoute
  '/lab/lesson': typeof LabLessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lab/design-system' | '/lab/lesson'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lab/design-system' | '/lab/lesson'
  id: '__root__' | '/' | '/lab/design-system' | '/lab/lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabDesignSystemRoute: typeof LabDesignSystemRoute
  LabLessonRoute: typeof LabLessonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/design-system': {
      id: '/lab/design-system'
      path: '/lab/design-system'
      fullPath: '/lab/design-system'
      preLoaderRoute: typeof LabDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/lesson': {
      id: '/lab/lesson'
      path: '/lab/lesson'
      fullPath: '/lab/lesson'
      preLoaderRoute: typeof LabLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabDesignSystemRoute: LabDesignSystemRoute,
  LabLessonRoute: LabLessonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
