/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses.$courseSlug'
import { Route as EgeIndexRouteImport } from './routes/ege.index'
import { Route as EgeSlugRouteImport } from './routes/ege.$slug'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeTaskIdRouteImport } from './routes/practice.$taskId'
import { Route as SitemapPracticePageRouteImport } from './routes/sitemap-practice.$page'
import { Route as CoursesCourseSlugLessonSlugRouteImport } from './routes/courses_.$courseSlug.$lessonSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EgeIndexRoute = EgeIndexRouteImport.update({
  id: '/ege/',
  path: '/ege/',
  getParentRoute: () => rootRouteImport,
} as any)
const EgeSlugRoute = EgeSlugRouteImport.update({
  id: '/ege/$slug',
  path: '/ege/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTaskIdRoute = PracticeTaskIdRouteImport.update({
  id: '/practice/$taskId',
  path: '/practice/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPracticePageRoute = SitemapPracticePageRouteImport.update({
  id: '/sitemap-practice/$page',
  path: '/sitemap-practice/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugLessonSlugRoute =
  CoursesCourseSlugLessonSlugRouteImport.update({
    id: '/courses_/$courseSlug/$lessonSlug',
    path: '/courses/$courseSlug/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/consent': typeof ConsentRoute
  '/password-reset': typeof PasswordResetRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/ege/$slug': typeof EgeSlugRoute
  '/practice/$taskId': typeof PracticeTaskIdRoute
  '/sitemap-practice/$page': typeof SitemapPracticePageRoute
  '/courses/': typeof CoursesIndexRoute
  '/ege/': typeof EgeIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/courses/$courseSlug/$lessonSlug': typeof CoursesCourseSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/consent': typeof ConsentRoute
  '/password-reset': typeof PasswordResetRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/ege/$slug': typeof EgeSlugRoute
  '/practice/$taskId': typeof PracticeTaskIdRoute
  '/sitemap-practice/$page': typeof SitemapPracticePageRoute
  '/courses': typeof CoursesIndexRoute
  '/ege': typeof EgeIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/courses/$courseSlug/$lessonSlug': typeof CoursesCourseSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/consent': typeof ConsentRoute
  '/password-reset': typeof PasswordResetRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-in': typeof SignInRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/ege/$slug': typeof EgeSlugRoute
  '/practice/$taskId': typeof PracticeTaskIdRoute
  '/sitemap-practice/$page': typeof SitemapPracticePageRoute
  '/courses/': typeof CoursesIndexRoute
  '/ege/': typeof EgeIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/courses_/$courseSlug/$lessonSlug': typeof CoursesCourseSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/consent'
    | '/password-reset'
    | '/privacy'
    | '/register'
    | '/robots.txt'
    | '/sign-in'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/verify-email'
    | '/courses/$courseSlug'
    | '/ege/$slug'
    | '/practice/$taskId'
    | '/sitemap-practice/$page'
    | '/courses/'
    | '/ege/'
    | '/practice/'
    | '/courses/$courseSlug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/consent'
    | '/password-reset'
    | '/privacy'
    | '/register'
    | '/robots.txt'
    | '/sign-in'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/verify-email'
    | '/courses/$courseSlug'
    | '/ege/$slug'
    | '/practice/$taskId'
    | '/sitemap-practice/$page'
    | '/courses'
    | '/ege'
    | '/practice'
    | '/courses/$courseSlug/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/consent'
    | '/password-reset'
    | '/privacy'
    | '/register'
    | '/robots.txt'
    | '/sign-in'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/verify-email'
    | '/courses/$courseSlug'
    | '/ege/$slug'
    | '/practice/$taskId'
    | '/sitemap-practice/$page'
    | '/courses/'
    | '/ege/'
    | '/practice/'
    | '/courses_/$courseSlug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ConsentRoute: typeof ConsentRoute
  PasswordResetRoute: typeof PasswordResetRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignInRoute: typeof SignInRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRoute
  EgeSlugRoute: typeof EgeSlugRoute
  PracticeTaskIdRoute: typeof PracticeTaskIdRoute
  SitemapPracticePageRoute: typeof SitemapPracticePageRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  EgeIndexRoute: typeof EgeIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  CoursesCourseSlugLessonSlugRoute: typeof CoursesCourseSlugLessonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ege/': {
      id: '/ege/'
      path: '/ege'
      fullPath: '/ege/'
      preLoaderRoute: typeof EgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ege/$slug': {
      id: '/ege/$slug'
      path: '/ege/$slug'
      fullPath: '/ege/$slug'
      preLoaderRoute: typeof EgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$taskId': {
      id: '/practice/$taskId'
      path: '/practice/$taskId'
      fullPath: '/practice/$taskId'
      preLoaderRoute: typeof PracticeTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-practice/$page': {
      id: '/sitemap-practice/$page'
      path: '/sitemap-practice/$page'
      fullPath: '/sitemap-practice/$page'
      preLoaderRoute: typeof SitemapPracticePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$courseSlug/$lessonSlug': {
      id: '/courses_/$courseSlug/$lessonSlug'
      path: '/courses/$courseSlug/$lessonSlug'
      fullPath: '/courses/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof CoursesCourseSlugLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ConsentRoute: ConsentRoute,
  PasswordResetRoute: PasswordResetRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignInRoute: SignInRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CoursesCourseSlugRoute: CoursesCourseSlugRoute,
  EgeSlugRoute: EgeSlugRoute,
  PracticeTaskIdRoute: PracticeTaskIdRoute,
  SitemapPracticePageRoute: SitemapPracticePageRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  EgeIndexRoute: EgeIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  CoursesCourseSlugLessonSlugRoute: CoursesCourseSlugLessonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
