/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/client-errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Client Error */
        post: operations["reportClientError"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Answer */
        post: operations["check_answer_api_tasks__task_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Alias */
        get: operations["health_alias_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalloutBlock */
        CalloutBlock: {
            data: components["schemas"]["CalloutBlockData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "callout";
        };
        /** CalloutBlockData */
        CalloutBlockData: {
            /** Markdown */
            markdown: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "info" | "warning";
        };
        /** CheckRequest */
        CheckRequest: {
            /** Answer */
            answer: string;
        };
        /** CheckResponse */
        CheckResponse: {
            /** Correct */
            correct: boolean;
            /** Explanation */
            explanation: (components["schemas"]["TextBlock"] | components["schemas"]["FigureBlock"] | components["schemas"]["DiagramBlock"] | components["schemas"]["CodeExampleBlock"] | components["schemas"]["WorkedExampleBlock"] | components["schemas"]["CalloutBlock"] | components["schemas"]["VideoEmbedBlock"])[];
        };
        /**
         * ClientErrorReport
         * @description Bounded diagnostic fields only; free-form exception data is deliberately forbidden.
         */
        ClientErrorReport: {
            /** Asset Path */
            asset_path?: string | null;
            /** Column */
            column?: number | null;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "render" | "route_load" | "chunk_load" | "unhandled_error" | "unhandled_rejection";
            /** Line */
            line?: number | null;
            /** Route Id */
            route_id: string;
        };
        /** CodeExampleBlock */
        CodeExampleBlock: {
            data: components["schemas"]["CodeExampleBlockData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code_example";
        };
        /** CodeExampleBlockData */
        CodeExampleBlockData: {
            /** Caption */
            caption?: string | null;
            /** Code */
            code: string;
            /** Language */
            language: string;
        };
        /** DiagramBlock */
        DiagramBlock: {
            /** Data */
            data: components["schemas"]["GraphDiagramData"] | components["schemas"]["TableDiagramData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "diagram";
        };
        /** DiagramElement */
        DiagramElement: {
            /** From */
            from?: string | null;
            /** Highlighted */
            highlighted?: boolean | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "node" | "edge" | "arrow" | "label" | "highlight";
            /** Text */
            text?: string | null;
            /** To */
            to?: string | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
        };
        /** FigureBlock */
        FigureBlock: {
            data: components["schemas"]["FigureBlockData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "figure";
        };
        /** FigureBlockData */
        FigureBlockData: {
            /** Alt */
            alt: string;
            /** Caption */
            caption?: string | null;
            /** Height */
            height: number;
            /** Src */
            src: string;
            /** Width */
            width: number;
        };
        /** GraphDiagramData */
        GraphDiagramData: {
            /** Arialabel */
            ariaLabel: string;
            /** Elements */
            elements: components["schemas"]["DiagramElement"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "automaton" | "graph";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** TableDiagramData */
        TableDiagramData: {
            /** Arialabel */
            ariaLabel: string;
            /** Headers */
            headers: string[];
            /** Highlightedcells */
            highlightedCells?: string[] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "bit-grid";
            /** Rows */
            rows: string[][];
        };
        /** TextBlock */
        TextBlock: {
            data: components["schemas"]["TextBlockData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        /** TextBlockData */
        TextBlockData: {
            /** Markdown */
            markdown: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoEmbedBlock */
        VideoEmbedBlock: {
            data: components["schemas"]["VideoEmbedBlockData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video_embed";
        };
        /** VideoEmbedBlockData */
        VideoEmbedBlockData: {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** WorkedExampleBlock */
        WorkedExampleBlock: {
            data: components["schemas"]["WorkedExampleBlockData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "completion_exercise" | "productive_failure_prompt" | "worked_example";
        };
        /** WorkedExampleBlockData */
        WorkedExampleBlockData: {
            /** Prompt */
            prompt: string;
            /** Steps */
            steps: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reportClientError: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientErrorReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_answer_api_tasks__task_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_alias_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
