"""practice_model"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "114_01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_object",
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=80), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_file_object_size")),
        sa.PrimaryKeyConstraint("checksum", name=op.f("pk_file_object")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_file_object_storage_key")),
        schema="practice",
    )
    op.create_table(
        "import_outcome",
        sa.Column("package_id", sa.String(length=120), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("task_count", sa.Integer(), nullable=False),
        sa.Column(
            "committed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("package_id", name=op.f("pk_import_outcome")),
        schema="practice",
    )
    op.create_table(
        "material",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material")),
        schema="practice",
    )
    op.create_table(
        "task",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("answer_instruction", sa.Text(), nullable=False),
        sa.Column("interaction_type", sa.String(length=20), nullable=False),
        sa.Column("statement", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_schema_version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("solution_revision", sa.Integer(), nullable=False),
        sa.Column("catalog_visible", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(hint) = 'array' AND jsonb_typeof(explanation) = 'array'",
            name=op.f("ck_task_blocks"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(statement) = 'array' AND jsonb_array_length(statement)>0",
            name=op.f("ck_task_statement"),
        ),
        sa.CheckConstraint("NOT (archived AND catalog_visible)", name=op.f("ck_task_visibility")),
        sa.CheckConstraint("content_schema_version = 1", name=op.f("ck_task_content_version")),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 3", name=op.f("ck_task_difficulty")),
        sa.CheckConstraint(
            "estimated_minutes IS NULL OR estimated_minutes > 0", name=op.f("ck_task_minutes")
        ),
        sa.CheckConstraint(
            "revision > 0 AND solution_revision > 0", name=op.f("ck_task_revisions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task")),
        schema="practice",
    )
    op.create_index(
        op.f("ix_task_catalog_visible"),
        "task",
        ["catalog_visible"],
        unique=False,
        schema="practice",
    )
    op.create_table(
        "lesson_task",
        sa.Column("material_id", sa.String(length=160), nullable=False),
        sa.Column("task_id", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_lesson_task_position")),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["practice.material.id"],
            name=op.f("fk_lesson_task_material_id_material"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["practice.task.id"], name=op.f("fk_lesson_task_task_id_task")
        ),
        sa.PrimaryKeyConstraint("material_id", "task_id", name=op.f("pk_lesson_task")),
        sa.UniqueConstraint(
            "material_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name=op.f("uq_lesson_task_material_id"),
        ),
        schema="practice",
    )
    op.create_index("ix_lesson_task_task_id", "lesson_task", ["task_id"], schema="practice")
    op.create_table(
        "material_section",
        sa.Column("material_id", sa.String(length=160), nullable=False),
        sa.Column("section", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["practice.material.id"],
            name=op.f("fk_material_section_material_id_material"),
        ),
        sa.PrimaryKeyConstraint("material_id", "section", name=op.f("pk_material_section")),
        schema="practice",
    )
    op.create_table(
        "provenance",
        sa.Column("task_id", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("primary", sa.Boolean(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("original_id", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("adaptation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"], ["practice.task.id"], name=op.f("fk_provenance_task_id_task")
        ),
        sa.PrimaryKeyConstraint("task_id", "position", name=op.f("pk_provenance")),
        schema="practice",
    )
    op.create_table(
        "task_checker",
        sa.Column("task_id", sa.String(length=120), nullable=False),
        sa.Column("checker_type", sa.String(length=30), nullable=False),
        sa.Column("answer_variants", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("numeric_tolerance", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "checker_type IN ('exact_match','numeric_tolerance')", name=op.f("ck_task_checker_type")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(answer_variants)='array' AND jsonb_array_length(answer_variants)>0",
            name=op.f("ck_task_checker_answers"),
        ),
        sa.CheckConstraint(
            "numeric_tolerance IS NULL OR numeric_tolerance >= 0",
            name=op.f("ck_task_checker_tolerance"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["practice.task.id"], name=op.f("fk_task_checker_task_id_task")
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_task_checker")),
        schema="practice",
    )
    op.create_table(
        "task_exam_number",
        sa.Column("task_id", sa.String(length=120), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.CheckConstraint("number BETWEEN 1 AND 27", name=op.f("ck_task_exam_number_number")),
        sa.ForeignKeyConstraint(
            ["task_id"], ["practice.task.id"], name=op.f("fk_task_exam_number_task_id_task")
        ),
        sa.PrimaryKeyConstraint("task_id", "number", name=op.f("pk_task_exam_number")),
        schema="practice",
    )
    op.create_index(
        op.f("ix_task_exam_number_number"),
        "task_exam_number",
        ["number"],
        unique=False,
        schema="practice",
    )
    op.create_table(
        "task_file_usage",
        sa.Column("task_id", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["checksum"],
            ["practice.file_object.checksum"],
            name=op.f("fk_task_file_usage_checksum_file_object"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["practice.task.id"], name=op.f("fk_task_file_usage_task_id_task")
        ),
        sa.PrimaryKeyConstraint("task_id", "id", name=op.f("pk_task_file_usage")),
        schema="practice",
    )
    op.create_table(
        "task_history",
        sa.Column("task_id", sa.String(length=120), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("solution_revision", sa.Integer(), nullable=False),
        sa.Column("package_id", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["practice.import_outcome.package_id"],
            name=op.f("fk_task_history_package_id_import_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["practice.task.id"], name=op.f("fk_task_history_task_id_task")
        ),
        sa.PrimaryKeyConstraint("task_id", "revision", name=op.f("pk_task_history")),
        schema="practice",
    )
    op.create_table(
        "task_skill",
        sa.Column("task_id", sa.String(length=120), nullable=False),
        sa.Column("skill", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["practice.task.id"], name=op.f("fk_task_skill_task_id_task")
        ),
        sa.PrimaryKeyConstraint("task_id", "skill", name=op.f("pk_task_skill")),
        schema="practice",
    )
    op.create_index(
        op.f("ix_task_skill_skill"), "task_skill", ["skill"], unique=False, schema="practice"
    )
    op.create_table(
        "theory_reference",
        sa.Column("task_id", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.String(length=160), nullable=False),
        sa.Column("section", sa.String(length=120), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id", "section"],
            ["practice.material_section.material_id", "practice.material_section.section"],
            name=op.f("fk_theory_reference_material_id_material_section"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["practice.task.id"], name=op.f("fk_theory_reference_task_id_task")
        ),
        sa.PrimaryKeyConstraint("task_id", "position", name=op.f("pk_theory_reference")),
        schema="practice",
    )
    # The importer appends immutable objects/journal entries and never owns release metadata.
    op.execute(
        "REVOKE INSERT, UPDATE, DELETE ON practice.alembic_version, "
        "practice.material, practice.material_section FROM infraege_import"
    )
    op.execute(
        "REVOKE UPDATE, DELETE ON practice.task_history, "
        "practice.import_outcome, practice.file_object FROM infraege_import"
    )


def downgrade():
    raise RuntimeError("destructive downgrade requires a separately reviewed recovery procedure")
