PermitRootLogin yes
PasswordAuthentication yes
KbdInteractiveAuthentication no
PubkeyAuthentication no
PermitEmptyPasswords no
AllowUsers root
X11Forwarding no
AllowTcpForwarding yes
MaxAuthTries 3
LoginGraceTime 30
